# Generated by Django 6.0.4 on 2026-04-30 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='💰', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('stk_push', 'STK Push (Pay)'), ('c2b', 'Customer to Business'), ('b2c', 'Business to Customer')], default='stk_push', max_length=20)),
                ('purpose', models.CharField(blank=True, choices=[('vet_services', 'Veterinary Services'), ('feed', 'Animal Feed'), ('medicine', 'Medicine'), ('transport', 'Transport'), ('animal_purchase', 'Animal Purchase'), ('animal_sale', 'Animal Sale'), ('product_sale', 'Product Sale (Milk/Eggs)'), ('equipment', 'Equipment'), ('labour', 'Labour'), ('other', 'Other')], max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mpesa_receipt', models.CharField(blank=True, help_text='M-Pesa confirmation code', max_length=50)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, help_text='Reference to related record (animal, health record, etc.)', max_length=100)),
                ('is_expense', models.BooleanField(default=True, help_text='True = expense, False = income')),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
