# Generated by Django 6.0.4 on 2026-04-30 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🐄', help_text='Emoji icon for display', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Animal Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_id', models.CharField(help_text='Unique ear tag or identification number', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_from', models.CharField(blank=True, max_length=200)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in kg', max_digits=8, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('died', 'Died'), ('transferred', 'Transferred'), ('sick', 'Sick')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='accounts.farm')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animalcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchased', 'Purchased'), ('sold', 'Sold'), ('died', 'Died'), ('transferred_in', 'Transferred In'), ('transferred_out', 'Transferred Out')], max_length=20)),
                ('date', models.DateField()),
                ('from_location', models.CharField(blank=True, max_length=200)),
                ('to_location', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='animals.animal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='animals.animalcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.breed'),
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('checkup', 'Checkup'), ('deworming', 'Deworming'), ('surgery', 'Surgery'), ('other', 'Other')], default='checkup', max_length=20)),
                ('date', models.DateField()),
                ('vet_name', models.CharField(blank=True, help_text='Veterinarian who performed the service', max_length=200)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('medicine', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_due_date', models.DateField(blank=True, help_text='Next vaccination or checkup date', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animals.animal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('milk', 'Milk Production'), ('eggs', 'Egg Production'), ('weight', 'Weight Check')], max_length=20)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Litres for milk, count for eggs, kg for weight', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Production Record',
                'verbose_name_plural': 'Production Records',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('farm', 'tag_id')},
        ),
    ]
