# Generated by Django 6.0.4 on 2026-04-30 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('animal', 'Live Animal'), ('milk', 'Milk'), ('eggs', 'Eggs'), ('feed', 'Animal Feed'), ('equipment', 'Farm Equipment'), ('other', 'Other Products')], default='animal', max_length=20)),
                ('description', models.TextField(help_text='Describe the animal/product, health status, breed, age, etc.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=12)),
                ('negotiable', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=200)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animal')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='accounts.farm')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketplace Listing',
                'verbose_name_plural': 'Marketplace Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text="Buyer's inquiry message")),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, help_text="Buyer's proposed price", max_digits=12, null=True)),
                ('phone_number', models.CharField(help_text="Buyer's phone number for contact", max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('seller_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_inquiries', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='marketplace.marketplacelisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
