# Generated by Django 6.0.4 on 2026-04-30 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed_type', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('twice_daily', 'Twice Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_schedules', to='accounts.farm')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('feeding', 'Feeding Reminder'), ('vet', 'Vet Appointment'), ('vaccination', 'Vaccination Due'), ('payment', 'Payment Confirmation'), ('marketplace', 'Marketplace Update'), ('health', 'Health Alert'), ('system', 'System Notification'), ('production', 'Production Alert'), ('other', 'Other')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('related_id', models.CharField(blank=True, max_length=100)),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
